Fix: Remove updated_at column from project and workspace updates
The projects and workspaces tables don't have updated_at columns in the schema.
This was causing 500 errors when trying to rename projects or workspaces.
Error: column "updated_at" of relation "projects" does not exist